### ISSUE TITLE
Particle texture is missing when eating

### ISSUE THREAD

**Issue by TerdyTheTerd** [Daniel-Tomov/AddHearts#4]
You get the missing texture when eating a heart. Looks like the "particle" texture is not setup correctly. I was able to resolve this by changing it to the fully qualified name, such as "item/heart/black" instead of just "black".

**Comment by Daniel-Tomov** [comment]
Thank you for the information. This is fixed in 720623ece62a1efd5f259d74ad4c36950cbba107. I set the particle texture to red instead of black because it seems more fitting.
